### ISSUE TITLE
The Terminator [NPUZ00056] freeze and crash when resuming the vita from suspend mode.

### ISSUE THREAD

**Issue by alpakeno** [qwikrazor87/npdrm_free#2]
Added npdrm_free v7.1 to vsh.txt or both vsh.txt and game.txt still not fixing the issue.

**Comment by qwikrazor87** [comment]
This issue should now be fixed in v7.2.
https://github.com/qwikrazor87/npdrm_free/releases

**Comment by alpakeno** [comment]
Thank you. confirm working now.
