### ISSUE TITLE
Where the heck is ms0 thing at?

### ISSUE THREAD

**Issue by Marioh2451** [qwikrazor87/npdrm_free#3]
Title says it.

**Comment by CelesteBlue-dev** [comment]
On PSVita ms0: is mounted over ux0:pspemu/.

**Comment by Marioh2451** [comment]
Oh yes i understood, thx (sorry for late comment) now games works after error 80010087

**Comment by CelesteBlue-dev** [comment]
so you launch the game, the error message appears you close the message then the game starts ?

**Comment by Marioh2451** [comment]
Again late reply, no start game, errors appears and Game doesn't work. With this Fix It solved my problem

**Comment by qwikrazor87** [comment]
I assume this issue is resolved, closing.
